import {passBeforeRemaining} from '../scripts/remaining-preservation-helpers.mjs';
import {partsBeforeCombat,registryBeforeCombat} from '../scripts/combat-preservation-helpers.mjs';
import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import{createHash}from'node:crypto';
import{SKILL_LABELING_CATALOG as catalog}from'../dist/skill-labeling-catalog.mjs';import{canonicalSkillRows,labelingView,skillLabelRows,filterLabelRows,resolveSkillLabels}from'../dist/skill-labeling-model.mjs';import{validateBreakCoverage,validateBreakBinding}from'../scripts/validate-break-labels.mjs';import{tagDetailsBeforeBreak}from'./break-preservation-helpers.mjs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'),r=JSON.parse(read('docs/skill-labeling-registry.json')),audit=JSON.parse(read('docs/break-tag-audit.json')),preserved=JSON.parse(read('docs/break-preservation-2026-09-25.json')),box={window:{}};vm.runInNewContext(read('dist/data.js'),box);const data=box.window.SKILL_DATA,rows=canonicalSkillRows(data),entry=n=>catalog.entries.find(e=>e.url.endsWith('/'+n)),bs=n=>entry(n).tagDetails.Break.bindings,hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),view=labelingView(catalog,'break'),nums=es=>es.map(e=>+e.url.split('/').pop()).sort((a,b)=>a-b);
const included=[126,163,190,191,295,809,840,850,1008,1009,1065,1085,1142,1280,1304,1458,1546,1665,1673,1675,1728,1764];

test('Break audits all 935 canonical records with exact scope and offensive stun, excluding resistance, guard release and race killers',()=>{
 assert.equal(audit.rows.length,935);assert.equal(new Set(audit.rows.map(x=>x.id)).size,935);assert.deepEqual(nums(view.entries),included);assert.equal(view.childKeys.length,23);assert.equal(view.entries.reduce((n,e)=>n+e.tagDetails.Break.bindings.length,0),28);
 for(const row of rows){const a=audit.rows.find(x=>x.id===row.id);assert.equal(a.sourceHash,hash([row.id,row.url,row.name,row.effect,row.notes||'']));assert.equal(a.decision==='related',view.entries.some(e=>e.id===row.id));}
 assert.deepEqual([...new Set(view.childKeys.flatMap(k=>labelingView(catalog,k).entries.map(e=>e.id)))].sort(),view.entries.map(e=>e.id).sort());for(const n of[36,194,348,1189,772,789,860,889,1691,1815,1913])assert(!view.entries.some(e=>e.url.endsWith('/'+n)));
 assert.deepEqual(view.counts,{reviewedUnique:935,relatedUnique:22,notRelatedUnique:913,ready:20,partial:2,unknown:0});assert.deepEqual(nums(view.entries.filter(e=>e.judgment==='partial')),[126,809]);assert.equal(catalog.entries.length,935);assert.equal(r.tagPasses.length,90);assert.equal(catalog.views.all.counts.ready,757);assert.equal(catalog.views.all.counts.partial,178);
});

test('Break retains all 898 previous sources and fragments, 70 assignments, original bindings, order and protected files',()=>{
 assert.equal(preserved.entries.length,898);assert.equal(preserved.tagPassHashes.length,70);assert.equal(preserved.noteUpdates.length,11);
 for(const old of preserved.entries){const e=r.entries.find(e=>e.id===old.id);assert.equal(hash([e.id,e.url,e.name,e.text,e.notes,partsBeforeCombat(e)]),old.sourceAndPartsHash,e.name);assert.equal(hash(tagDetailsBeforeBreak(e)),old.tagDetailsHash,e.name);}
 for(const p of preserved.tagPassHashes)assert.equal(hash(passBeforeRemaining(r.tagPasses.find(x=>x.tag===p.tag))),p.hash,p.tag);for(const[p,h]of Object.entries(preserved.protectedFiles))assert.equal(createHash('sha256').update(read(p)).digest('hex'),h,p);
 assert.deepEqual(r.views.all.displayOrder.slice(0,898),preserved.previousDisplayOrder);assert.equal(catalog.numericEffectInjection,false);
 const preCombat=registryBeforeCombat(r),currentBeforeCombat=resolveSkillLabels(preCombat),before={...preCombat,entries:preCombat.entries.filter(e=>preserved.entries.some(p=>p.id===e.id)),tagPasses:preCombat.tagPasses.filter(p=>p.tag!=='Break')},prior=resolveSkillLabels(before);assert.equal(prior.filter(e=>e.judgment==='ready').length,605);
 assert.deepEqual(nums(prior.filter(e=>e.judgment==='partial'&&currentBeforeCombat.find(x=>x.id===e.id).judgment==='ready')),[163,295,840,1008,1009,1065,1085,1142,1280,1304,1458,1546,1665,1675,1728]);for(const e of prior.filter(e=>e.judgment==='ready'))assert.equal(entry(+e.url.split('/').pop()).judgment,'ready');
});

test('Break gauge values preserve physical, skill, axe and weapon-count limits with additive branches and identity reuse',()=>{
 const base=bs(191)[0];assert.equal(base.valuePercent,50);assert.equal(base.scope.attackType,'unspecified');assert.equal(base.changesHpDamage,false);assert.equal(base.appliesBreakImmediately,false);
 for(const n of[163,1304]){const b=bs(n)[0];assert.deepEqual(b.scope.equipment,{weaponType:'axe',minimumMatchingWeaponCount:1});assert.equal(b.scope.attackType,'unspecified');assert.equal(b.perMatchingWeaponStacking,false);assert.equal(b.valuePercent,20);assert.equal(entry(n).judgment,'ready');}
 const one=bs(850)[0];assert.equal(one.scope.attackType,'physical');assert.equal(one.scope.equipment.weaponCount,1);assert.equal(one.valuePercent,100);assert.equal(one.effectIdentity,entry(850).tagDetails['物理'].bindings[0].effectIdentity);
 const zero=bs(1458)[0];assert.deepEqual(zero.scope.equipment,{weaponCount:0});assert.equal(zero.scope.attackType,'unspecified');assert.equal(zero.valuePercent,100);
 const skill=bs(1764).find(b=>b.partIds.includes('skill-break')),extra=bs(1764).find(b=>b.addsToPartId);assert.equal(skill.scope.attackType,'skill');assert.equal(skill.scope.equipment,undefined);assert.equal(skill.valuePercent,30);assert.equal(extra.scope.equipment.weaponCount,1);assert.equal(extra.scope.attackType,'skill');assert.equal(extra.valuePercent,30);assert.equal(extra.addsToPartId,'skill-break');assert.deepEqual(entry(1764).remainingEffects,[]);
 for(const b of bs(1764))assert.equal(b.effectIdentity,entry(1764).tagDetails['特技相关'].bindings.find(x=>x.partIds[0]===b.partIds[0]).effectIdentity);
});

test('Break states preserve the whole OR, element and damage channel without completing independent displayed effects',()=>{
 const damage=bs(190)[0];assert.deepEqual(damage.scope.enemyStateAnyOf,['stunned','break']);assert.equal(damage.statePredicate.logicalOperator,'OR');assert.equal(damage.matchingMultipleStates,'apply-once');assert.equal(damage.changesBreakGaugeDamage,false);assert.equal(damage.scope.attackType,'unspecified');assert(!entry(190).assignedTags.includes('伤害增加'));
 const only=bs(295)[0];assert.equal(only.scope.enemyState,'break');assert.equal(only.scope.enemyStateAnyOf,undefined);assert.equal(only.scope.attackType,'physical');assert.equal(only.valuePercent,30);
 for(const[n,element]of[[840,'ice'],[1008,'fire'],[1546,'fire'],[1065,'dark'],[1728,'dark'],[1085,'earth'],[1142,'light'],[1665,'light'],[1280,'thunder'],[1675,'thunder']])for(const b of bs(n)){assert.equal(b.scope.element,element);assert.equal(b.scope.attackType,'unspecified');assert.deepEqual(b.scope.enemyStateAnyOf,['stunned','break']);assert.equal(b.statePredicate.subject,'target-enemy');assert.equal(b.matchingMultipleStates,'apply-once');assert.equal(b.breakRole,'condition-benefit');assert.equal(entry(n).tagDetails.Break.coverage.effectPartIds.length,0);if(b.operation==='cap-up'){assert.equal(b.capPoints,3000);assert.equal(b.valuePercent,undefined);}else assert.equal(b.valuePercent,20);assert.equal(entry(n).judgment,'ready');}
 for(const a of r.tagPasses.find(p=>p.tag==='Break').assignments){const d=catalog.entries.find(e=>e.id===a.skillId).tagDetails.Break;for(const b of d.bindings.filter(b=>b.breakRole==='condition-benefit'))assert(b.partIds.every(id=>!a.partIds.includes(id)));}
});

test('opening Buff, elemental weakness and combo threshold keep their independent timing and pending mechanisms',()=>{
 const buff=bs(1009)[0];assert.equal(buff.valuePercent,50);assert.equal(buff.isBuff,true);assert.equal(buff.endsOn,'incapacitated');assert.equal(buff.durationSeconds,undefined);assert.equal(buff.trigger.event,'battle-start');assert.equal(buff.stacking,'highest-active-buff-of-same-type-only');assert.deepEqual(entry(1009).remainingEffects,[]);assert.equal(entry(1009).tagDetails['暴击'].bindings[0].ratePoints,15);
 const weak=bs(809)[0];assert.equal(weak.scope.requiresElementWeakHit,true);assert.equal(weak.condition.checksTargetForThisHit,true);assert.equal(weak.scope.attackType,'unspecified');assert.equal(weak.valuePercent,50);assert(entry(809).assignedTags.includes('属性弱点'));assert(entry(809).remainingConditions.some(t=>t.includes('气绝')));
 const combo=bs(1673)[0];assert.deepEqual(combo.condition,{subject:'combo',metric:'consecutive-hit-count',operator:'gte',threshold:50});assert.equal(combo.activeByDefault,false);assert.equal(combo.valuePercent,30);assert.deepEqual(entry(1673).remainingEffects,[]);assert.equal(entry(1673).remainingConditions.length,0);
 for(const a of r.tagPasses.find(p=>p.tag==='Break').assignments){const e=r.entries.find(e=>e.id===a.skillId),d=e.tagDetails.Break;validateBreakCoverage(catalog.views.break,d,a,e);for(const b of d.bindings)validateBreakBinding(d,a,b);}
 const reject=(n,change)=>{const d=entry(n).tagDetails.Break,b=structuredClone(bs(n)[0]),a=r.tagPasses.find(p=>p.tag==='Break').assignments.find(a=>a.skillId===entry(n).id);change(b);assert.throws(()=>validateBreakBinding(d,a,b));};reject(191,b=>b.changesHpDamage=true);reject(191,b=>b.appliesBreakImmediately=true);reject(1009,b=>b.durationSeconds=40);reject(1009,b=>b.stacking='sum');reject(190,b=>b.statePredicate.logicalOperator='AND');reject(190,b=>b.matchingMultipleStates='stack');reject(295,b=>b.scope.enemyState='stunned');reject(840,b=>b.breakRole='direct-effect');reject(809,b=>b.condition.checksTargetForThisHit=false);reject(1673,b=>b.condition.operator='gt');reject(1673,b=>b.condition.subject='self-received-hits');
});

function page(){const elements=new Map(),get=k=>{if(!elements.has(k))elements.set(k,{value:'',textContent:'',innerHTML:'',hidden:false,listeners:{},addEventListener(k,v){this.listeners[k]=v},setAttribute(){},focus(){}});return elements.get(k)};vm.runInNewContext(read('dist/skill-labeling.mjs').replace(/^import .*;\n/gm,'').replace('export function renderLabelTable','function renderLabelTable'),{catalog,skillLabelRows,labelingView,filterLabelRows,URLSearchParams,document:{querySelector:get},window:{SKILL_DATA:data,location:{search:'?tag=break'},addEventListener(){}},localStorage:{getItem:()=>null,setItem(){assert.fail('Preserve user saves')}}});return get;}
test('Break page renders 23 groups, sorts judgments, deduplicates search and discards stale labels after edits',()=>{
 const get=page();assert.equal(get('#activeTagTitle').textContent,'Break');assert.match(get('#judgmentSummary').textContent,/20.*2.*0/);assert.equal((get('#labelTabs').innerHTML.match(/role="tab"/g)||[]).length,82);const sections=get('#labelTable').innerHTML.split('<section ').slice(1);assert.equal(sections.length,23);for(const s of sections){const ranks=[...s.matchAll(/judgment-label judgment-(ready|partial|unknown)/g)].map(m=>({ready:0,partial:1,unknown:2})[m[1]]);assert.deepEqual(ranks,[...ranks].sort((a,b)=>a-b));}
 get('#labelSearch').value=entry(1546).name;get('#labelSearch').listeners.input();assert.match(get('#labelResultCount').textContent,/显示 1 \//);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,2);const edited=skillLabelRows(data,view,{['skill:'+entry(191).id]:{effect:'新效果'}}).find(e=>e.id===entry(191).id);assert.equal(edited.judgment,'unknown');assert.deepEqual(edited.assignedTags,[]);
});
