import test from 'node:test';
import assert from 'node:assert/strict';
import {magicBuffOptions,magicBuffCap,magicBuffLayer} from '../dist/magic-buffs.mjs';
import {panelObservation,capturePanelObservation,readerPanelSnapshots,defaultReaderSnapshot,observedReaderUnit} from '../dist/battle-entry-data.mjs';
import {ACCOUNT_BLESSING_CATALOG,USER_CONFIRMED_BLESSING_RECORDS} from '../dist/account-blessings.mjs';
import {retargetReport,validateBattleEntry,websiteCandidates,compareCandidates,decisionKey,resolveReview} from '../dist/entry-preparation.mjs';
import {buildBonusComparison} from '../dist/bonus-comparison.mjs';
import {readerSupplementCandidates} from '../dist/reader-supplements.mjs';
import {evaluateCatalog} from '../dist/effect-rule-engine.mjs';
import {CATALOG} from '../dist/roxy-rules.mjs';
import {calculateWebsitePanel} from '../dist/panel-calculator.mjs';
import {resolveAttackLayers,needsAttributeLayers} from '../dist/attack-layers.mjs';
import {buildDamageImport} from '../dist/damage-import.mjs';
import {defaultInput,calculate} from '../dist/damage-engine.mjs';
const context={attack:'magic',damageType:'magical',element:'ice',weaponCount:1,staff:true,robe:true,equipmentIds:['roxy-staff','roxy-robe'],fullHp:true,chainStacks:1,accountBlessings:true};
const profile={baseStats:{hp:10702,mp:459,attack:1222,defense:1407,intelligence:2512,mind:1619},equipment:[{name:'洛琪希之魔杖',type:'法杖'},{name:'洛琪希的衣服',type:'长袍'}],magic:[{name:'魔术指导',description:'为一名我方单位赋予INT+65%、魔法伤害上限+30,000的增益'}]};
test('user-confirmed 1% migrates old reports, maps to its source, and is counted exactly once',()=>{
 const old={kind:'last-cloudia-effect-report',characterId:'260',...evaluateCatalog([...CATALOG,...ACCOUNT_BLESSING_CATALOG.filter(b=>b.localId!==60002460)],context)};
 const r=retargetReport(old,{attack:'magic',type:'magical',element:'冰'});
 assert.equal(r.rows.filter(r=>r.sourceId==='account-blessing-60002460').length,1);
 const bonus=validateBattleEntry({kind:'last-cloudia-battle-entry',schemaVersion:1,units:[{stats:{},bonuses:USER_CONFIRMED_BLESSING_RECORDS}]}).units[0].bonuses[0];
 assert.equal(bonus.sourceName,'加护 · 长袍 · 魔法伤害');assert.equal(bonus.value,1);
 assert.equal(bonus.decoded.accountBlessing.identificationBasis,'user-confirmed-account-blessing');
 const web=websiteCandidates(r),other=web.filter(w=>w.effect.target==='魔法伤害'&&w.sourceId!=='account-blessing-60002460').map((w,i)=>({id:`other-${i}`,sourceName:w.sourceName,sourceId:w.sourceId,effectType:'damage',target:'魔法伤害',value:w.effect.value,unit:'%',decoded:{conditions:w.condition}}));
 const bonuses=[bonus,...other],compared=compareCandidates(web,bonuses,{},r.context),group=buildBonusComparison(compared,bonuses,r.context).find(g=>g.target==='魔法伤害');
 assert.equal(group.total,40);assert.equal(group.readTotal,40);assert(group.canUseReader);
 assert.equal(readerSupplementCandidates(bonuses,compared,r.context).length,0);
 const decisions=Object.fromEntries(compared.map(row=>[decisionKey(row),{choice:row.sourceId==='account-blessing-60002460'?'reader':'web'}]));
 const imported=buildDamageImport(resolveReview(r,compared,decisions));
 assert.equal(imported.effects.filter(e=>e.name.includes('加护 · 长袍 · 魔法伤害')).length,1);
 assert.equal(imported.hitScaleStage,'core');
});
test('reader observation timestamps remain distinct, missing later DEF/MND never get invented',()=>{
 const unit={unitId:502220,capturedAt:'entry-time',stats:{intelligence:6741,defense:1621,mind:2808}},battle={battleId:'entry-id',capturedAt:'updated-time',collection:{buffApplicationVerified:false}};
 assert.equal(panelObservation(battle,unit,'intelligence').time,'entry-time');
 const sample={explicitSelection:true,unitId:502220,stats:{intelligence:10111},capturedAt:'attack-time',sampleId:'csv-group'};
 const later=capturePanelObservation(battle,unit,sample);
 assert.equal(panelObservation(battle,unit,'intelligence',later).value,10111);
 assert.equal(panelObservation(battle,unit,'defense',later).value,1621);
 assert.equal(unit.stats.intelligence,6741);
 assert.equal(capturePanelObservation(battle,unit,{...sample,unitId:123}),null);
 assert.equal(capturePanelObservation(battle,unit,{...sample,explicitSelection:false}),null);
});
test('guidance replaces the same-group EX buff while preserving independent HP effects',()=>{
 const buffs=magicBuffOptions(profile);assert.equal(buffs.length,1);
 assert.equal(magicBuffOptions({magic:[{...profile.magic[0],description:'法强+65%'}]}).length,0);
 assert.equal(magicBuffCap([], 'magic'),0);assert.equal(magicBuffCap(buffs,'skill'),0);assert.equal(magicBuffCap(buffs,'magic'),30000);
 assert.equal(magicBuffCap(buffs,'magic',[{source:'魔术指导',effect:{type:'cap',target:'魔法伤害上限',value:30000}}]),0);
 const stat={key:'intelligence',beforeBuff:6741,crossAdd:0,buffs:[{family:'ex-aura',value:50,source:'EX'},{family:'moonlight-ii',value:30,source:'月光'}]};
 const projected=magicBuffLayer(stat,10111,buffs);assert(projected.ok);
 assert.equal(projected.observedPanel,10111);
 assert.equal(projected.percent,65);assert.equal(projected.panel,11122);assert.equal(projected.replaced[0].family,'ex-aura');
 const full=magicBuffLayer(stat,12133,buffs);assert.equal(full.percent,95);assert.equal(full.panel,13144);assert(full.active.some(b=>b.family==='moonlight-ii'));
 assert.equal(magicBuffLayer(stat,6741,buffs).percent,65);
 const observed=magicBuffLayer(stat,11122,buffs);assert(observed.ok&&observed.buffObserved);assert.equal(observed.percent,65);assert.equal(observed.projected,undefined);
 assert.equal(magicBuffLayer(stat,13144,buffs).percent,95);
 for(const invalid of [14493,16515])assert.equal(magicBuffLayer(stat,invalid,buffs).ok,false);
 assert.equal(magicBuffLayer(stat,10000,buffs).ok,false);
 const common={...defaultInput(),attackBasis:'layers',coefficient:.52,skillPercent:67,defense:8000,type:'magical',skillType:'magic',element:'冰',resistance:50,specialAttack:true,killerCorrection:50,hits:35,hitMultiplier:2,hitDamageRatio:.6,hitScaleStage:'core',cap:200000,critRate:0,effects:[]};
 const calculated=[projected,full].map(layer=>calculate({...common,attackBase:layer.base,runtimeStatPercent:layer.percent}));
 assert.deepEqual(calculated.map(r=>r.context.attack),[15639,17661]);assert(calculated.every(r=>r.normal.min>0&&r.totalHits===70));

});
test('exact reported wrong range is the old panel mode, and the normal layer guard prevents it',()=>{
 const report=evaluateCatalog([...CATALOG,...ACCOUNT_BLESSING_CATALOG],context);
 const stat=calculateWebsitePanel(profile.baseStats,report,{equipment:profile.equipment}).stats.intelligence;
 const s={...defaultInput(),attackBasis:'panel',attack:10111,coefficient:.52,skillPercent:67,defense:8000,type:'magical',skillType:'magic',element:'冰',resistance:50,specialAttack:true,killerCorrection:50,hits:35,hitMultiplier:2,hitDamageRatio:.6,hitScaleStage:'beforeCap',cap:200000,critRate:0,effects:[50,30,20,15,20,30,30,30,4,20,35,4.06].map(percent=>({percent,kind:'magical',stage:'post',enabled:true}))};
 const old=calculate(s);assert.deepEqual([old.normal.min,old.normal.max],[40267,44740]);
 assert(needsAttributeLayers(s.attackBasis,stat,s.attack));
 const layer=resolveAttackLayers(stat,s.attack);assert(layer.ok);
 const fixed=calculate({...s,attackBasis:'layers',attackBase:layer.base,runtimeStatPercent:layer.percent,hitScaleStage:'core',effects:[...s.effects,{percent:1,kind:'magical',stage:'post',enabled:true}]});
 assert.deepEqual([fixed.normal.min,fixed.normal.max],[32611,36247]);assert.equal(fixed.context.attack,14627);
 assert.equal(needsAttributeLayers('panel',stat,6741),false);
 assert.equal(needsAttributeLayers('settlement',stat,10111),false);
 // Removing all runtime sources cannot re-enable the old multiplication path.
 assert(needsAttributeLayers('panel',{...stat,buffs:[]},10111));
 assert.equal(resolveAttackLayers({...stat,buffs:[]},10111).ok,false);
});

test('latest stable snapshot is used as one complete observed panel; invalid/unfinished snapshots cannot replace it',()=>{
 const initial={hp:13591,mp:1018,attack:1270,defense:1621,intelligence:6741,mind:2808,critical:11};
 const stable={...initial,defense:2295,intelligence:10111,mind:3482,critical:6};
 const unit={stats:initial,statsMeta:{criticalRate:11},panelSnapshots:[{id:'panel-1',elapsedMs:0,stableForMs:1000,stats:initial},{id:'panel-2',capturedAt:'later',elapsedMs:1000,stableForMs:750,stats:stable},{id:'panel-3',elapsedMs:2000,stableForMs:0,stats:{...stable,intelligence:12133}},{id:'invalid',elapsedMs:3000,stableForMs:2000,stats:{intelligence:30000}}],latestStablePanelSnapshotId:'panel-2'};
 assert.equal(readerPanelSnapshots(unit).length,3);assert.equal(defaultReaderSnapshot(unit),'panel-2');
 for(const [key,value] of Object.entries(stable))assert.equal(panelObservation({},unit,key).value,value);
 assert.equal(panelObservation({},unit,'intelligence',{},'entry').value,6741);
 assert.equal(panelObservation({},unit,'intelligence',{},'panel-3').value,12133);
 assert.equal(observedReaderUnit(unit).statsMeta.criticalRate,6);assert.equal(unit.statsMeta.criticalRate,11);
 assert.equal(defaultReaderSnapshot({...unit,latestStablePanelSnapshotId:'invalid'}),'entry');
 assert.equal(defaultReaderSnapshot({...unit,latestStablePanelSnapshotId:'panel-3'}),'entry');
});
