import {ADDITIONAL_RACE_TAGS,partsBeforeRaces} from './race-preservation-helpers.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createHash} from 'node:crypto';
import {SKILL_LABELING_CATALOG as catalog} from '../dist/skill-labeling-catalog.mjs';import {canonicalSkillRows,labelingView,skillLabelRows,filterLabelRows} from '../dist/skill-labeling-model.mjs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8'),registry=JSON.parse(read('../docs/skill-labeling-registry.json')),audit=JSON.parse(read('../docs/critical-tag-audit.json'));
const box={window:{}};vm.runInNewContext(read('../dist/data.js'),box);const data=box.window.SKILL_DATA,all=canonicalSkillRows(data),view=labelingView(catalog,'critical');const source=n=>all.find(r=>r.url.endsWith(`/gino/${n}`)),entry=n=>catalog.entries.find(e=>e.id===source(n).id),detail=n=>entry(n).tagDetails['暴击'];const nums=v=>v.entries.map(e=>Number(e.url.split('/').pop())).sort((a,b)=>a-b);
const included=[25,26,27,28,29,37,141,142,143,144,145,146,201,216,225,237,239,252,268,272,285,286,292,329,332,341,365,377,390,410,502,556,594,600,619,763,977,1009,1177,1211,1263,1289,1519,1775,1884];
test('critical review covers every unique skill and follows effects rather than critical-sounding names',()=>{
 assert.equal(audit.rows.length,935);assert.equal(new Set(audit.rows.map(r=>r.id)).size,935);assert.equal(audit.matchedUnique,45);assert.deepEqual(nums(view),included);
 for(const r of all){const a=audit.rows.find(a=>a.id===r.id);assert.equal(a.sourceHash,createHash('sha256').update(JSON.stringify([r.id,r.url,r.name,r.effect,r.notes||''])).digest('hex'));assert.equal(a.decision==='related',view.entries.some(e=>e.id===r.id));}
 for(const n of [184,389,1264,1744])assert(!view.entries.some(e=>e.id===source(n).id));
 assert.equal(view.childKeys.length,49);assert.equal(view.childKeys.reduce((n,k)=>n+catalog.views[k].counts.relatedUnique,0),56);assert.equal(catalog.entries.length,935);assert.equal(new Set(catalog.entries.map(e=>e.id)).size,935);
 assert.deepEqual(nums(labelingView(catalog,'critical-rate-general')),[25,26,27]);assert.deepEqual(nums(labelingView(catalog,'critical-damage-general')),[28,216,1775]);
});
test('rate, damage, cap, permission and incoming defense retain their distinct units, directions and scopes',()=>{
 for(const [n,v] of [[25,2],[26,5],[27,8]]){const b=detail(n).bindings[0];assert.equal(b.ratePoints,v);assert.equal(b.valuePercent,undefined);assert.equal(b.grantsCriticalEligibility,false);}
 for(const [n,v] of [[28,30],[216,50],[1775,15]]){const b=detail(n).bindings[0];assert.equal(b.operation,'damage-up');assert.equal(b.valuePercent,v);assert.equal(b.requiresCriticalHit,true);assert.equal(b.ratePoints,undefined);}
 for(const [n,element] of [[141,'fire'],[142,'ice'],[143,'earth'],[144,'thunder'],[145,'light'],[146,'dark']]){const b=detail(n).bindings[0];assert.equal(b.operation,'enable-critical');assert.equal(b.scope.element,element);assert.equal(b.scope.attackType,'attack-magic');assert.equal(b.guaranteedCritical,false);assert.equal(b.ratePoints,undefined);assert.equal(entry(n).judgment,'ready');}
 for(const [n,element] of [[252,'thunder'],[286,'fire'],[292,'light'],[329,'none'],[332,'earth'],[341,'dark'],[377,'ice']]){const [r,d]=detail(n).bindings;assert.equal(r.ratePoints,5);assert.equal(d.valuePercent,50);assert.equal(r.scope.element,element);assert.equal(d.scope.element,element);assert(r.group.startsWith('rate-'));assert(d.group.startsWith('damage-'));assert.equal(entry(n).judgment,'ready');}
 for(const b of detail(268).bindings)assert.deepEqual(b.scope,{direction:'outgoing',attackType:'physical',position:'behind'});
 for(const [n,type] of [[365,'spear'],[410,'hammer'],[502,'sword'],[556,'axe'],[594,'claw'],[619,'machine'],[977,'bow']]){const b=detail(n).bindings[0];assert.deepEqual(b.scope.equipment,{weaponCount:1,weaponType:type});assert.equal(b.operation,'rate-up');assert.equal(b.ratePoints,10);assert(!entry(n).remainingEffects.some(x=>x.includes('上限')));}
 assert.equal(detail(285).bindings[0].scope.attackType,'unspecified');for(const n of [600,1211])assert.equal(detail(n).bindings[0].scope.attackType,'physical');assert.equal(detail(1263).bindings[0].scope.attackType,'counter');
 assert.equal(detail(225).bindings[0].scope.enemyRace,'ore');for(const b of detail(1289).bindings)assert.equal(b.scope.enemyIsBoss,true);assert.equal(detail(1289).bindings[1].capPoints,2000);
 for(const b of detail(1519).bindings){assert.equal(b.scope.attackType,'physical');assert.equal(b.scope.hitsElementWeakness,true);assert.equal(b.requiresCriticalHit,true);assert.equal(b.scope.enemyRace,undefined);}
 const [cap,permission]=detail(1884).bindings;assert.equal(cap.capPoints,100000);assert.deepEqual(cap.trigger,{event:'battle-start'});assert.equal(permission.trigger,undefined);assert.equal(permission.guaranteedCritical,false);for(const b of [cap,permission])assert.deepEqual(b.scope,{direction:'outgoing',attackType:'ultimate',selfRace:'dragon'});
 for(const n of [763,1177]){const b=detail(n).bindings[0];assert.equal(b.scope.direction,'incoming');assert.equal(b.operation,'incoming-damage-down');assert.equal(b.valuePercent,10);}
 const conversion=detail(37).bindings[0];assert.equal(conversion.operation,'convert-to-normal');assert.equal(conversion.chancePercent,50);assert.equal(conversion.valuePercent,undefined);assert(entry(37).remainingConditions.includes('触发概率50%'));
 const heal=detail(29);assert.deepEqual(heal.condition,{subject:'self-attack',event:'critical-hit'});assert.equal(heal.bindings[0].criticalRole,'condition-benefit');assert.equal(heal.bindings[0].amountStatus,'unconfirmed');assert.equal(entry(29).judgment,'partial');
});
test('critical Buff lifetimes and shared labels complete only fully covered skills',()=>{
 for(const n of [201,272,390]){const b=detail(n).bindings[0];assert.equal(b.durationSeconds,40);assert.equal(b.buffType,'critical-rate-up');assert.equal(b.stacking,'highest-active-buff-of-same-type-only');}
 assert.equal(detail(239).bindings[0].lifetime,'permanent');assert.equal(detail(239).bindings[0].durationSeconds,undefined);assert.equal(detail(1009).bindings[0].endsOn,'incapacitated');assert.equal(detail(1009).bindings[0].durationSeconds,undefined);assert.equal(detail(237).bindings[0].isBuff,false);
 assert.equal(registry.tagPasses.length,91);assert.equal(catalog.numericEffectInjection,false);const p=registry.tagPasses.find(p=>p.tag==='暴击');for(const a of p.assignments){const e=catalog.entries.find(e=>e.id===a.skillId),d=e.tagDetails['暴击'];assert.deepEqual(a.partIds,[...d.coverage.effectPartIds,...d.coverage.conditionPartIds]);for(const b of d.bindings.filter(b=>b.criticalRole==='condition-benefit'))assert(b.partIds.every(id=>!a.partIds.includes(id)));}
 assert.deepEqual(view.entries.filter(e=>e.judgment==='ready').map(e=>Number(e.url.split('/').pop())).sort((a,b)=>a-b),[25,26,27,28,141,142,143,144,145,146,201,216,225,237,239,252,268,285,286,292,329,332,341,365,377,390,410,502,556,594,600,619,763,977,1009,1177,1211,1263,1289,1519,1884]);
 assert.deepEqual(entry(272).assignedTags.filter(tag=>!['物理','魔法','鸟','Boss','铠甲','衣服','法袍','防御','魔抗','伤害减少','异常','Break','格挡','反击','普通攻击','追击','HP回复','吸血','杂项','属性弱点','连击','击败敌人','战斗结束','空中','背后攻击','队伍联动','战斗时间','距离','HP持续消耗','致命伤害存活','通用伤害上限','触发次数与重置',...ADDITIONAL_RACE_TAGS].includes(tag)),['攻击力','魔力','复活','暴击']);assert.deepEqual(entry(272).remainingEffects,[]);assert(entry(272).remainingConditions.length);assert.equal(entry(390).judgment,'ready');assert.equal(entry(1884).judgment,'ready');assert.deepEqual(entry(1884).remainingConditions,[]);
 for(const [n,k] of [[201,'battle-start'],[237,'full-hp'],[239,'battle-start'],[1177,'hp'],[1177,'defense'],[1289,'boss-critical-damage']])assert.equal(labelingView(catalog,k).entries.find(e=>e.id===source(n).id).judgment,'ready');
 assert.equal(view.counts.ready,41);assert.equal(view.counts.partial,4);assert.equal(catalog.views.all.counts.ready,749);assert.equal(catalog.views.all.counts.partial,186);
});
function page(edits={}){const elements=new Map(),get=k=>{if(!elements.has(k))elements.set(k,{value:'',textContent:'',innerHTML:'',hidden:false,listeners:{},addEventListener(k,v){this.listeners[k]=v;},setAttribute(){},focus(){}});return elements.get(k);};const code=read('../dist/skill-labeling.mjs').replace(/^import .*;\n/gm,'').replace('export function renderLabelTable','function renderLabelTable');vm.runInNewContext(code,{catalog,skillLabelRows,labelingView,filterLabelRows,URLSearchParams,document:{querySelector:get},window:{SKILL_DATA:data,location:{search:'?tag=critical'},addEventListener(){}},localStorage:{getItem:()=>JSON.stringify(edits),setItem(){assert.fail('Do not modify saved data.');}}});return {get,click:(nav,tag)=>get(nav).listeners.click({target:{closest:()=>({dataset:{tag}})}})};}
test('critical overview deduplicates multi-effect skills and retains old views, sorting and edited-description review',()=>{
 const {get,click}=page();assert.match(get('#labelCoverage').textContent,/935.*45.*890/);assert.match(get('#judgmentSummary').textContent,/41.*4.*0/);assert.match(get('#labelResultCount').textContent,/45 \/ 45/);assert.equal((get('#labelTabs').innerHTML.match(/role="tab"/g)||[]).length,83);assert.equal((get('#labelSubTabs').innerHTML.match(/role="tab"/g)||[]).length,50);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,49);
 const search=get('#labelSearch');search.value='雷暴击提升';search.listeners.input();assert.match(get('#labelResultCount').textContent,/1 \/ 45/);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,2);get('#clearLabelSearch').listeners.click();click('#labelSubTabs','critical-permission-ice');assert(get('#labelTable').innerHTML.includes('冰暴击'));assert(!get('#labelTable').innerHTML.includes('冰霜暴击提升'));
 for(const [k,n] of [['ally-death',7],['revive',6],['mp',32],['ultimate',113],['received-attack',21],['full-hp',6],['low-hp',26],['battle-start',117],['boss',31]]){click('#labelTabs',k);assert.equal(get('#labelResultCount').textContent,`显示 ${n} / ${n} 个技能（去重）`);}
 const sorted=skillLabelRows(data,view);assert(sorted.slice(0,41).every(r=>r.judgment==='ready'));assert(sorted.slice(41).every(r=>r.judgment==='partial'));
 const edits={[`skill:${source(25).id}`]:{effect:'未知效果'},[`skill:${source(9).id}`]:{effect:'新增暴击效果'}};const changed=page(edits);assert.match(changed.get('#labelResultCount').textContent,/46 \/ 46/);assert.match(changed.get('#labelTable').innerHTML,/描述已修改，待重新判断（2）/);const stale=skillLabelRows(data,view,edits).find(e=>e.id===source(25).id);assert.equal(stale.judgment,'unknown');assert.deepEqual(stale.conditionBindings,{});
});
