import {textBeforeCommonCalculator} from '../scripts/calculator-preservation-helpers.mjs';
import {passBeforeRemaining} from '../scripts/remaining-preservation-helpers.mjs';
import {tagDetailsBeforeBreak} from './break-preservation-helpers.mjs';
import {partsBeforeAbnormal} from '../scripts/validate-abnormal-labels.mjs';
import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import{createHash}from'node:crypto';
import{SKILL_LABELING_CATALOG as catalog}from'../dist/skill-labeling-catalog.mjs';import{canonicalSkillRows,labelingView,skillLabelRows,filterLabelRows,resolveSkillLabels}from'../dist/skill-labeling-model.mjs';import{defensiveKeys,validateDefensiveCoverage,validateDefensiveBinding}from'../scripts/validate-defensive-labels.mjs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'),r=JSON.parse(read('docs/skill-labeling-registry.json')),preserved=JSON.parse(read('docs/defensive-preservation-2026-09-25.json')),box={window:{}};vm.runInNewContext(read('dist/data.js'),box);const data=box.window.SKILL_DATA,rows=canonicalSkillRows(data),entry=n=>catalog.entries.find(e=>e.url.endsWith('/'+n)),label=k=>catalog.views[k].label,bs=(n,k)=>entry(n).tagDetails[label(k)].bindings,hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),nums=es=>es.map(e=>+e.url.split('/').pop()).sort((a,b)=>a-b),newTags=[...defensiveKeys.map(label),'异常','Break','格挡','反击','普通攻击','追击','HP回复','吸血','杂项','属性弱点','连击','击败敌人','战斗结束','空中','背后攻击','队伍联动','战斗时间','距离','HP持续消耗','致命伤害存活','通用伤害上限','触发次数与重置','装备自身数值强化','地面状态','自身倒下／战斗不能'];

test('all three defensive passes audit 935 canonical sources, preserve groups and scope their members',()=>{
 for(const[k,total,groups]of[['defense',123,56],['mnd',77,37],['damage-reduction',14,8]]){const v=labelingView(catalog,k),a=JSON.parse(read('docs/'+k+'-tag-audit.json'));assert.equal(v.entries.length,total);assert.equal(v.childKeys.length,groups);assert.equal(a.rows.length,935);assert.equal(new Set(a.rows.map(x=>x.id)).size,935);for(const row of rows){const q=a.rows.find(x=>x.id===row.id);assert.equal(q.sourceHash,hash([row.id,row.url,row.name,row.effect,row.notes||'']));assert.equal(q.decision==='related',v.entries.some(e=>e.id===row.id));}assert.deepEqual([...new Set(v.childKeys.flatMap(c=>labelingView(catalog,c).entries.map(e=>e.id)))].sort(),v.entries.map(e=>e.id).sort());}
 for(const a of r.tagPasses.find(p=>p.tag==='防御力').assignments)assert(labelingView(catalog,'defense').entries.some(e=>e.id===a.skillId));
 for(const n of [30,31,32,34,35,36,38,104,107,182,204,212,233,306,482,638,915,1133,1176,1692,1754,1881])assert(entry(n).assignedTags.includes('防御'));
 for(const n of [21,22,23,24,33,105,109,110,116,203,220,221,350,430,740,993,1074,1092,1306,1449,1754,1755,1813,1847,1989,2016])assert(entry(n).assignedTags.includes('魔抗'));
 for(const n of [104,107,246,244,294,521,638,763,776,842,873,888,942,1097,1123,1177,1281,1307,1366,1497,1527,1606,1630,1692,1755,1811,1812,1881,1989])assert(!entry(n)?.assignedTags.includes('伤害减少'),String(n));
 assert.deepEqual(nums(labelingView(catalog,'damage-reduction').entries),[389,628,655,699,731,780,859,976,992,1036,1075,1478,1481,1490]);
 assert.equal(catalog.entries.length,935);assert.equal(r.tagPasses.length,93);assert.equal(catalog.views.all.counts.ready,787);assert.equal(catalog.views.all.counts.partial,148);
});

test('every old source, fragment, binding, tag pass, order and calculator file remains intact',()=>{
 assert.equal(preserved.entries.length,852);assert.equal(preserved.tagPassHashes.length,66);
 for(const old of preserved.entries){const e=r.entries.find(e=>e.id===old.id);assert.equal(hash([e.id,e.url,e.name,e.text,e.notes,partsBeforeAbnormal(e).filter(p=>p.id!=='mnd-healing-reference')]),old.sourceAndPartsHash,e.name);const d=Object.fromEntries(Object.entries(tagDetailsBeforeBreak(e)).filter(([t])=>!newTags.includes(t)));for(const fix of preserved.noteUpdates.filter(f=>f.skillId===e.id)){assert.equal(d[fix.tag].calculationNote,fix.after);d[fix.tag].calculationNote=fix.before;}assert.equal(hash(d),old.tagDetailsHash,e.name);}
 for(const p of preserved.tagPassHashes)assert.equal(hash(passBeforeRemaining(r.tagPasses.find(x=>x.tag===p.tag))),p.hash,p.tag);
 for(const[p,h]of Object.entries(preserved.protectedFiles))assert.equal(createHash('sha256').update(textBeforeCommonCalculator(p,read(p))).digest('hex'),h,p);
 assert.deepEqual(catalog.views.all.displayOrder.slice(0,87),catalog.views.attack.displayOrder);assert.equal(catalog.numericEffectInjection,false);
 const before=structuredClone(r);before.tagPasses=before.tagPasses.filter(p=>!newTags.includes(p.tag)).map(passBeforeRemaining);for(const e of before.entries)e.parts=partsBeforeAbnormal(e).filter(p=>p.id!=='mnd-healing-reference');const old=resolveSkillLabels(before);const currentBeforeAbnormal=resolveSkillLabels({...r,tagPasses:r.tagPasses.filter(p=>!['异常','Break','格挡','反击','普通攻击','追击','HP回复','吸血','杂项','属性弱点','连击','击败敌人','战斗结束','空中','背后攻击','队伍联动','战斗时间','距离','HP持续消耗','致命伤害存活','通用伤害上限','触发次数与重置','装备自身数值强化','地面状态','自身倒下／战斗不能'].includes(p.tag)).map(passBeforeRemaining),entries:r.entries.map(e=>({...e,parts:partsBeforeAbnormal(e)}))});
 const promotions=old.filter(e=>e.judgment==='partial'&&currentBeforeAbnormal.find(c=>c.id===e.id).judgment==='ready');assert.equal(promotions.length,26);for(const e of old.filter(e=>e.judgment==='ready'))assert.equal(entry(+e.url.split('/').pop()).judgment,'ready');
});

test('MND and DEF keep item bases, fixed points, reference semantics, Buffs and unknown curves separate',()=>{
 const fixed=bs(1969,'defense')[0];assert.equal(fixed.valuePoints,100);assert.equal(fixed.valuePercent,undefined);
 for(const n of [599,823,828,1059,1515,1940])for(const k of ['defense','mnd']){const b=bs(n,k)[0];assert.equal(b.base,'equipped-item-stat');assert.equal(b.target,'equipped-armor');assert.equal(b.pairedEquipmentLogicalOperator,'AND');assert.equal(entry(n).judgment,'ready');}
 for(const[n,k,pct]of[[524,'mnd',5],[1074,'defense',7],[1074,'mnd',7],[1813,'mnd',10]]){const b=bs(n,k)[0];assert.equal(b.referencePercent,pct);assert.equal(b.changesReferenceStat,false);assert.equal(b.valuePercent,undefined);assert.equal(entry(n).judgment,'ready');}
 for(const n of [110,220,1092]){const b=bs(n,'mnd')[0];assert.equal(b.completesHealingEffect,false);assert.equal(b.formulaStatus,'unconfirmed');assert.equal(entry(n).judgment,'partial');assert(entry(n).remainingConditions.some(t=>/回复.*公式/.test(t)));assert(entry(n).assignedTags.includes('HP回复'));}
 for(const[n,k]of[[788,'defense'],[1390,'defense'],[1390,'mnd'],[1765,'defense'],[915,'defense'],[1449,'mnd'],[1847,'mnd']]){const b=bs(n,k).find(b=>/scaled-/.test(b.operation));assert.equal(b.valuePercent,undefined);assert.equal(b.curveStatus??b.condition?.curveStatus,'unconfirmed');assert.equal(entry(n).judgment,'partial');}
 for(const k of ['defense','mnd'])for(const n of [118,890]){const b=bs(n,k)[0];assert.equal(b.maxTriggersPerWave,1);assert.equal(b.durationSeconds,40);assert.equal(b.persistsAfterHpRecovery,true);}
 assert.equal(bs(350,'mnd')[0].lifetime,'permanent');assert.equal(bs(203,'mnd')[0].durationSeconds,40);assert.equal(bs(740,'mnd')[0].chancePercent,5);assert.equal(bs(2016,'mnd')[0].durationStatus,'unconfirmed');
 assert.equal(bs(1133,'defense')[0].referencePercent,100);assert.equal(bs(1133,'defense')[0].valuePercent,undefined);assert.equal(bs(175,'defense')[0].appliesPersistentDebuff,false);assert.equal(bs(212,'defense')[0].target,'target-enemy');
});

test('typed mitigation is copied without widening or new identities and generic reduction keeps every activation qualifier',()=>{
 for(const[k,tag,ops]of[['defense','物理',['incoming-damage-down','incoming-damage-up','mp-scaled-reduction','distance-scaled-reduction','tiered-incoming-damage-down']],['mnd','魔法',['incoming-damage-down','mp-scaled-reduction']]])for(const e of catalog.entries)for(const b of e.tagDetails[tag]?.bindings||[]){if(!ops.includes(b.operation)||b.classificationContext?.kind==='associated-drawback'||k==='mnd'&&b.scope.attackType!=='attack-magic')continue;const newer=e.tagDetails[label(k)].bindings.find(x=>x.effectIdentity===b.effectIdentity);for(const name of Object.keys(b).filter(n=>!['group','associatedGroups'].includes(n)))assert.deepEqual(newer[name],b[name],e.name+'/'+name);}
 for(const n of [780,1036]){assert.equal(bs(n,'damage-reduction')[0].condition.event,'counter-active');assert.equal(bs(n,'damage-reduction')[0].scope.attackType,'unspecified');}
 const end=bs(859,'damage-reduction')[0];assert.equal(end.endsOn,'hit-by-enemy-ice-attack');assert.equal(end.scope.element,undefined);assert.equal(end.valuePercent,5);
 const decay=bs(699,'damage-reduction')[0];assert.equal(decay.initialReductionPercent,10);assert.equal(decay.decayPercentagePoints,1);assert.equal(decay.decayIntervalSeconds,10);assert.equal(decay.valuePercent,undefined);
 const hits=bs(628,'damage-reduction')[0];assert.equal(hits.hitsAtMaximum,50);assert.equal(hits.maxReductionPercent,50);assert.equal(hits.curveStatus,'unconfirmed');assert.equal(hits.valuePercent,undefined);
 const party=bs(1075,'damage-reduction')[0].condition;assert.equal(party.otherAlliesWithSameSkill,1);assert.equal(party.operator,'eq');assert.equal(party.excludesSelf,true);
 assert.equal(bs(1478,'damage-reduction')[0].valuePercent,undefined);assert.equal(bs(976,'damage-reduction')[0].condition.incapacitatedAlliesQualify,false);
 for(const n of [34,35,204]){const b=bs(n,'defense')[0],a=r.tagPasses.find(p=>p.tag==='防御').assignments.find(a=>a.skillId===entry(n).id);assert.equal(b.familyRole,'condition-benefit');assert(b.partIds.every(id=>!a.partIds.includes(id)));assert.equal(entry(n).judgment,'partial');}
});

test('validators reject wrong damage types, false maxima, unknown completion, healing completion and Buff stacking',()=>{
 const reject=(n,k,mutate)=>{const d=entry(n).tagDetails[label(k)],b=structuredClone(d.bindings[0]),a=r.tagPasses.find(p=>p.tag===label(k)).assignments.find(a=>a.skillId===entry(n).id);mutate(b);assert.throws(()=>validateDefensiveBinding(k,d,a,b));};
 reject(1490,'damage-reduction',b=>b.scope.attackType='physical');reject(1490,'damage-reduction',b=>b.scope.attackerType='boss');reject(1490,'damage-reduction',b=>b.operation='incoming-damage-up');reject(628,'damage-reduction',b=>b.valuePercent=50);reject(699,'damage-reduction',b=>b.valuePercent=10);reject(1969,'defense',b=>b.valuePercent=100);reject(203,'mnd',b=>b.stacking='sum');reject(110,'mnd',b=>b.completesHealingEffect=true);reject(599,'mnd',b=>b.base='character-final-stat');reject(105,'mnd',b=>b.scope.attackType='physical');
 for(const k of defensiveKeys)for(const a of r.tagPasses.find(p=>p.tag===label(k)).assignments){const e=r.entries.find(e=>e.id===a.skillId),d=e.tagDetails[label(k)];validateDefensiveCoverage(catalog.views[k],d,a,e);for(const b of d.bindings)validateDefensiveBinding(k,d,a,b);}
});

function page(tag){const elements=new Map(),get=k=>{if(!elements.has(k))elements.set(k,{value:'',textContent:'',innerHTML:'',hidden:false,listeners:{},addEventListener(k,v){this.listeners[k]=v},setAttribute(){},focus(){}});return elements.get(k)};vm.runInNewContext(read('dist/skill-labeling.mjs').replace(/^import .*;\n/gm,'').replace('export function renderLabelTable','function renderLabelTable'),{catalog,skillLabelRows,labelingView,filterLabelRows,URLSearchParams,document:{querySelector:get},window:{SKILL_DATA:data,location:{search:'?tag='+tag},addEventListener(){}},localStorage:{getItem:()=>null,setItem(){assert.fail('Preserve user saves')}}});return get;}
test('original defense route and new MND/reduction pages render grouped results, deduplicate search and invalidate edits',()=>{
 for(const k of defensiveKeys){const get=page(k);assert.equal(get('#activeTagTitle').textContent,label(k));assert.equal((get('#labelTabs').innerHTML.match(/role="tab"/g)||[]).length,85);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,catalog.views[k].childKeys.length);assert(!get('#labelTabs').innerHTML.includes('防御力（70）'));for(const section of get('#labelTable').innerHTML.split('<section ').slice(1)){const ranks=[...section.matchAll(/judgment-label judgment-(ready|partial|unknown)/g)].map(m=>({ready:0,partial:1,unknown:2})[m[1]]);assert.deepEqual(ranks,[...ranks].sort((a,b)=>a-b));}const n=k==='defense'?638:k==='mnd'?875:731;get('#labelSearch').value=entry(n).name;get('#labelSearch').listeners.input();assert.match(get('#labelResultCount').textContent,/显示 1 \//);const edited=skillLabelRows(data,labelingView(catalog,k),{['skill:'+entry(n).id]:{effect:'新的效果'}}).find(e=>e.id===entry(n).id);assert.equal(edited.judgment,'unknown');assert.deepEqual(edited.assignedTags,[]);}
});
