import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createHash} from 'node:crypto';
import {SKILL_LABELING_CATALOG as catalog} from '../dist/skill-labeling-catalog.mjs';import {canonicalSkillRows,labelingView,skillLabelRows,filterLabelRows} from '../dist/skill-labeling-model.mjs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8'),registry=JSON.parse(read('../docs/skill-labeling-registry.json')),audit=JSON.parse(read('../docs/fire-tag-audit.json'));
const box={window:{}};vm.runInNewContext(read('../dist/data.js'),box);const data=box.window.SKILL_DATA,all=canonicalSkillRows(data),view=labelingView(catalog,'fire');const source=n=>all.find(r=>r.url.endsWith(`/gino/${n}`)),entry=n=>catalog.entries.find(e=>e.id===source(n).id),detail=n=>entry(n).tagDetails['火属性'];const nums=v=>v.entries.map(e=>Number(e.url.split('/').pop())).sort((a,b)=>a-b);
const included=[73,127,134,141,214,244,286,345,346,359,450,451,582,643,648,662,663,700,883,1008,1038,1229,1379,1397,1459,1546,1548,1572,1640,1659,1882,1954];
const ready=[73,127,134,141,214,286,345,359,450,451,582,643,648,662,663,700,883,1459,1572,1640,1954];
test('fire audits all skills, includes Ice Wall fire reduction and excludes names, other elements and generic variable-element scopes',()=>{
 assert.equal(audit.rows.length,935);assert.equal(new Set(audit.rows.map(r=>r.id)).size,935);assert.equal(audit.matchedUnique,32);assert.deepEqual(nums(view),included);
 for(const r of all){const a=audit.rows.find(a=>a.id===r.id);assert.equal(a.sourceHash,createHash('sha256').update(JSON.stringify([r.id,r.url,r.name,r.effect,r.notes||''])).digest('hex'));assert.equal(a.decision==='related',view.entries.some(e=>e.id===r.id));}
 for(const n of [74,128,142,252,272,381,439,508,691,836,938,1190,1272,1381,1519,1573,1604,1695,1746])assert(!view.entries.some(e=>e.id===source(n).id),source(n).name);
 assert.equal(view.childKeys.length,26);assert.equal(view.childKeys.reduce((n,k)=>n+catalog.views[k].counts.relatedUnique,0),46);assert.equal(catalog.entries.length,737);assert.equal(new Set(catalog.entries.map(e=>e.id)).size,737);
 for(const [group,ns] of [['damage-general',[73,359,648,883]],['damage-physical',[450,451,582,663,1572]],['damage-magic',[127,134,643,662,1640]],['damage-ultimate',[450,451,582,663,1572]],['received-passive',[345,346]],['received-opening',[214,1459]],['received-permanent',[700]],['received-random',[244]],['cap-weakness',[1038,1379,1882]]])assert.deepEqual(nums(labelingView(catalog,'fire-'+group)),ns);
});
test('fire effect scopes distinguish attack element, weapon condition, unrelated ultimate damage and remaining elemental branches',()=>{
 for(const n of [450,451,582,663,1572])assert(detail(n).bindings.filter(b=>b.operation==='damage-up').every(b=>['physical','ultimate'].includes(b.scope.attackType)));
 for(const n of [127,134,643,662,1640])assert(detail(n).bindings.every(b=>b.scope.attackType==='magic'));
 assert.equal(detail(582).bindings.filter(b=>b.operation==='cap-up').length,2);assert(detail(582).bindings.filter(b=>b.operation==='cap-up').every(b=>b.capPoints===2000));
 assert.equal(detail(883).bindings.length,1);assert.equal(detail(883).bindings[0].valuePercent,15);assert.deepEqual(entry(883).remainingEffects,[]);assert.equal(entry(883).tagDetails['必杀相关'].bindings[0].valuePercent,50);assert.equal(entry(883).tagDetails['必杀相关'].bindings[0].scope.element,undefined);
 for(const n of [662,663,1572,1640]){const p=registry.tagPasses.find(p=>p.tag==='火属性').assignments.find(a=>a.skillId===source(n).id);assert(p.partIds.every(id=>id.startsWith('fire-')));assert.equal(entry(n).judgment,'ready');assert.deepEqual(entry(n).remainingEffects,[]);}
 assert.deepEqual(detail(1548).coverage,{effectPartIds:[],conditionPartIds:['condition-2']});for(const b of detail(1548).bindings){assert.equal(b.fireRole,'condition-benefit');assert.equal(b.scope.element,undefined);assert.deepEqual(b.scope.equipment,{weaponType:'sword',weaponElement:'fire'});}
 assert(entry(1548).remainingEffects.includes('自身当前HP持续下降'));assert(!entry(1548).remainingEffects.includes('物理攻击伤害上限+2,000'));assert.deepEqual(entry(1548).remainingConditions,[]);
 const permission=detail(141).bindings[0];assert.equal(permission.scope.attackType,'attack-magic');assert.equal(permission.operation,'enable-critical');assert.equal(permission.guaranteedCritical,false);assert.equal(permission.ratePoints,undefined);
 assert.equal(detail(286).bindings[0].ratePoints,5);assert.equal(detail(286).bindings[1].valuePercent,50);assert.equal(detail(286).bindings[1].requiresCriticalHit,true);
});
test('fire Buffs preserve targets and random timing; conditional values do not silently use maxima or stack replacement branches',()=>{
 for(const [n,v] of [[214,20],[1459,35]]){const b=detail(n).bindings[0];assert.equal(b.target,'all-allies');assert.equal(b.valuePercent,v);assert.equal(b.durationSeconds,40);assert.equal(b.changesResistance,false);assert.equal(b.buffType,'received-fire-damage-down');assert.equal(b.stacking,'highest-active-buff-of-same-type-only');}
 const permanent=detail(700).bindings[0];assert.equal(permanent.target,'self');assert.equal(permanent.lifetime,'permanent');assert.equal(permanent.durationSeconds,undefined);
 const random=detail(244).bindings[0];assert.equal(random.intervalSeconds,10);assert.equal(random.durationSeconds,30);assert.equal(random.requiredSelectedStatus,'ice-wall');assert.equal(random.activeByDefault,false);assert.equal(random.target,'self');assert.equal(entry(244).remainingEffects.length,0);
 for(const n of [345,346])assert.equal(detail(n).bindings[0].isBuff,false);const opening=detail(1954).bindings[0];assert.equal(opening.buffType,'fire-damage-up');assert.equal(opening.durationSeconds,40);
 for(const [n,v] of [[1038,2000],[1379,1000],[1882,3000]]){const b=detail(n).bindings[0];assert.equal(b.capPoints,undefined);assert.equal(b.branches,'mutually-exclusive');assert.deepEqual(b.capCases,[{when:{weaponCount:1},capPoints:v*2},{otherwise:true,capPoints:v}]);assert.equal(b.scope.hitsElementWeakness,true);assert(entry(n).remainingConditions.length);}
 const ensemble=detail(1229).bindings[0];assert.equal(ensemble.countMetric,'allies-with-same-skill');assert.equal(ensemble.requiredSkillId,source(1229).id);assert.equal(ensemble.minimumCount,2);assert.deepEqual(ensemble.tiers,[{count:2,valuePercent:10},{count:3,valuePercent:20},{count:4,valuePercent:30}]);assert.equal(ensemble.valuePercent,undefined);
 assert.deepEqual(detail(1397).bindings[0].hitCount,{metric:'consecutive-hits',operator:'gte',value:50});for(const n of [1008,1546])for(const b of detail(n).bindings)assert.deepEqual(b.scope.enemyStateAnyOf,['stunned','break']);
 for(const b of detail(1659).bindings){assert.equal(b.scope.attackType,'skill');assert.equal(b.scaling.curveStatus,'unconfirmed');assert.equal(b.valuePercent,undefined);assert.equal(b.capPoints,undefined);}assert.equal(detail(1659).bindings[0].maxValuePercent,25);assert.equal(detail(1659).bindings[1].maxCapPoints,2000);
});
test('fire labels accumulate on stable identities and only complete their own effects and scopes',()=>{
 assert.equal(registry.tagPasses.length,44);assert.equal(catalog.numericEffectInjection,false);const p=registry.tagPasses.find(p=>p.tag==='火属性');for(const a of p.assignments){const e=catalog.entries.find(e=>e.id===a.skillId),d=e.tagDetails['火属性'];assert.deepEqual(a.partIds,[...d.coverage.effectPartIds,...d.coverage.conditionPartIds]);for(const b of d.bindings.filter(b=>b.fireRole==='condition-benefit'))assert(b.partIds.every(id=>!a.partIds.includes(id)));}
 assert.deepEqual(nums({entries:view.entries.filter(e=>e.judgment==='ready')}),ready);assert.equal(view.counts.ready,21);assert.equal(view.counts.partial,11);assert.equal(catalog.views.all.counts.ready,341);assert.equal(catalog.views.all.counts.partial,396);
 for(const n of [141,286]){assert.deepEqual(entry(n).assignedTags.filter(tag=>tag!=='物理'),['暴击','火属性']);assert.equal(labelingView(catalog,'critical').entries.find(e=>e.id===source(n).id).judgment,'ready');}
 for(const n of [214,700,1459,1954]){assert.deepEqual(entry(n).assignedTags.filter(tag=>tag!=='物理'),['战斗开始','火属性']);assert.equal(labelingView(catalog,'battle-start').entries.find(e=>e.id===source(n).id).judgment,'ready');}
 assert.deepEqual(entry(346).assignedTags.filter(tag=>tag!=='物理'),['物理伤害增加','火属性']);assert.equal(entry(346).judgment,'partial');assert(!entry(73).assignedTags.filter(tag=>tag!=='物理').includes('伤害增加'));assert(!entry(127).assignedTags.filter(tag=>tag!=='物理').includes('魔法伤害增加'));
});
function page(edits={}){const elements=new Map(),get=k=>{if(!elements.has(k))elements.set(k,{value:'',textContent:'',innerHTML:'',hidden:false,listeners:{},addEventListener(k,v){this.listeners[k]=v;},setAttribute(){},focus(){}});return elements.get(k);};const code=read('../dist/skill-labeling.mjs').replace(/^import .*;\n/gm,'').replace('export function renderLabelTable','function renderLabelTable');vm.runInNewContext(code,{catalog,skillLabelRows,labelingView,filterLabelRows,URLSearchParams,document:{querySelector:get},window:{SKILL_DATA:data,location:{search:"?tag=fire"},addEventListener(){}},localStorage:{getItem:()=>JSON.stringify(edits),setItem(){assert.fail('Do not modify saved data.');}}});return {get,click:(nav,tag)=>get(nav).listeners.click({target:{closest:()=>({dataset:{tag}})}})};}
test('fire groups deduplicate multi-effect searches and preserve old pages, status sorting and stale edit review',()=>{
 const {get,click}=page();assert.match(get('#labelCoverage').textContent,/935.*32.*903/);assert.match(get('#judgmentSummary').textContent,/21.*11.*0/);assert.match(get('#labelResultCount').textContent,/32 \/ 32/);assert.equal((get('#labelTabs').innerHTML.match(/role="tab"/g)||[]).length,39);assert.equal((get('#labelSubTabs').innerHTML.match(/role="tab"/g)||[]).length,27);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,26);
 const search=get('#labelSearch');search.value='炎属性超阶驱动';search.listeners.input();assert.match(get('#labelResultCount').textContent,/1 \/ 32/);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,4);get('#clearLabelSearch').listeners.click();click('#labelSubTabs','fire-received-opening');assert(get('#labelTable').innerHTML.includes('快速冰墙'));assert(!get('#labelTable').innerHTML.includes('快速炎壁'));
 for(const [k,n] of [['critical',45],['ally-death',7],['revive',6],['mp',32],['ultimate',113],['received-attack',21],['full-hp',6],['low-hp',26],['battle-start',117],['boss',13]]){click('#labelTabs',k);assert.equal(get('#labelResultCount').textContent,`显示 ${n} / ${n} 个技能（去重）`);}
 const sorted=skillLabelRows(data,view);assert(sorted.slice(0,21).every(r=>r.judgment==='ready'));assert(sorted.slice(21).every(r=>r.judgment==='partial'));
 const edits={[`skill:${source(73).id}`]:{effect:'未知效果'},[`skill:${source(9).id}`]:{effect:'新增火属性效果'}};const changed=page(edits);assert.match(changed.get('#labelResultCount').textContent,/33 \/ 33/);assert.match(changed.get('#labelTable').innerHTML,/描述已修改，待重新判断（2）/);const stale=skillLabelRows(data,view,edits).find(e=>e.id===source(73).id);assert.equal(stale.judgment,'unknown');assert.deepEqual(stale.conditionBindings,{});
});
