import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import{createHash}from'node:crypto';
import{SKILL_LABELING_CATALOG as catalog}from'../dist/skill-labeling-catalog.mjs';import{canonicalSkillRows,labelingView,skillLabelRows,filterLabelRows,resolveSkillLabels}from'../dist/skill-labeling-model.mjs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8'),registry=JSON.parse(read('../docs/skill-labeling-registry.json')),box={window:{}};vm.runInNewContext(read('../dist/data.js'),box);const data=box.window.SKILL_DATA,rows=canonicalSkillRows(data),source=n=>rows.find(r=>r.url.endsWith('/'+n)),entry=n=>catalog.entries.find(e=>e.id===source(n).id),d=(n,tag)=>entry(n).tagDetails[tag];
const specs=[['axe','斧',[80,163,555,556,1304,1484,1689,1690,1746],12,21,5],['spear','枪',[81,236,326,365,482,629,925,1410,1489,1515,1516,1704,1746],17,32,9],['hammer','锤',[82,273,281,410,1107,1109,1369,1518],9,20,7],['bow','弓',[83,977,1230],6,6,3],['machine','机械',[84,398,418,570,619,1014,1365,1746,1940],14,20,6],['claw','爪',[85,285,396,594,599,600,1211,1251,1538],15,22,8],['staff','杖',[86,241,354,641,658,1059],9,12,4]];
test('seven weapon reviews cover all 935 source identities, with no race, name-only or generic weapon leakage',()=>{
 const union=new Set();let appearances=0;
 for(const[k,tag,ns,groups,apps,ready]of specs){const a=JSON.parse(read('../docs/'+k+'-tag-audit.json')),v=labelingView(catalog,k);assert.deepEqual(v.entries.map(e=>+e.url.split('/').pop()).sort((a,b)=>a-b),ns);assert.equal(a.rows.length,935);assert.equal(new Set(a.rows.map(r=>r.id)).size,935);for(const r of rows){const ar=a.rows.find(x=>x.id===r.id);assert.equal(ar.sourceHash,createHash('sha256').update(JSON.stringify([r.id,r.url,r.name,r.effect,r.notes||''])).digest('hex'));assert.equal(ar.decision==='related',ns.includes(+r.url.split('/').pop()));}assert.equal(v.childKeys.length,groups);assert.equal(v.childKeys.reduce((n,c)=>n+catalog.views[c].counts.relatedUnique,0),apps);assert.equal(v.counts.ready,ready);assert.equal(v.counts.partial,ns.length-ready);v.entries.forEach(e=>union.add(e.id));appearances+=apps;
  for(const n of[55,56,176,181,327,424,577,616,715,738,789,1073,1191,1272,1573,1615,1756,1816])assert(!v.entries.some(e=>e.id===source(n).id));
 }assert.equal(union.size,55);assert.equal(appearances,133);assert.equal(catalog.entries.length,772);assert.equal(catalog.numericEffectInjection,false);
});
test('permission does not satisfy equipped conditions; Mochi Master does not restrict its unrelated cap to hammer',()=>{
 for(const[n,tag,key]of[[80,'斧','axe'],[81,'枪','spear'],[82,'锤','hammer'],[83,'弓','bow'],[84,'机械','machine'],[85,'爪','claw'],[86,'杖','staff'],[1518,'锤','hammer']]){const b=d(n,tag).bindings[0];assert.equal(b.operation,'allow-weapon-type');assert.equal(b.grantsWeaponType,key);assert.equal(b.automaticallyEquipsWeapon,false);assert.equal(b.scope.equipment,undefined);}
 assert.equal(d(1518,'锤').bindings.length,1);assert.equal(entry(1518).judgment,'partial');assert(!entry(1518).remainingEffects.some(s=>s.includes('20,000')));assert(entry(1518).assignedTags.filter(tag=>!['物理','魔法'].includes(tag)).includes('单手'));assert(entry(1518).remainingConditions.some(s=>s.includes('概率')));
 for(const[k,tag]of specs)for(const e of labelingView(catalog,k).entries)for(const b of e.tagDetails[tag].bindings){assert.equal(b.isBuff,false);assert.equal(b.perMatchingWeaponStacking,false);if(b.group.startsWith('single-'))assert.equal(b.scope.equipment.weaponCount,1);if(b.group.startsWith('equipped-'))assert.equal(b.scope.equipment.weaponCount,undefined);}
});
test('OR weapon branches and sword/claw AND combination keep shared identity and distinct conditions',()=>{
 const bs=['斧','枪','机械'].map(tag=>d(1746,tag).bindings[0]);assert.equal(new Set(bs.map(b=>b.effectIdentity)).size,1);for(const tag of['斧','枪','机械']){const detail=d(1746,tag);assert.equal(detail.condition.logicalOperator,'OR');assert.deepEqual(detail.condition.allowedWeaponTypesAnyOf,['axe','spear','machine']);const b=detail.bindings[0];assert.equal(b.valuePercent,15);assert.equal(b.scope.attackElementRelation,'same-as-equipped-weapon');assert.equal(b.scope.element,undefined);assert.equal(b.effectStacking,'once-per-skill');}assert.equal(entry(1746).remainingConditions.length,1);assert.equal(entry(1746).remainingEffects.length,1);assert.equal(entry(1746).judgment,'partial');
 for(const tag of['剑','爪'])for(const b of d(1538,tag).bindings){assert.deepEqual(b.scope.equipment.weaponTypesAllOf,['sword','claw']);assert.equal(b.scope.equipment.weaponCount,2);assert.equal(b.scope.equipment.sameElement,undefined);}assert.deepEqual(entry(1538).remainingConditions,[]);assert.equal(entry(1538).judgment,'ready');assert(!entry(1538).remainingEffects.some(x=>x.includes('上限')));
});
test('effect groups preserve equipment bases, incoming direction, DEF reference and independent special conditions',()=>{
 for(const[n,tag,armor]of[[1690,'斧','armor'],[1515,'枪','clothes'],[599,'爪','clothes'],[1940,'机械','clothes'],[641,'杖','robe'],[1059,'杖','clothes']])for(const b of d(n,tag).bindings){assert.equal(b.base,'equipped-item-stat');assert.equal(b.scope.equipment.armorType,armor);assert(entry(n).remainingConditions.some(s=>s.includes('同时装备')));}
 for(const n of[236,326,629,1489])assert.equal(d(n,'枪').bindings.find(b=>b.operation==='damage-reduction').scope.direction,'incoming');
 for(const n of[398,418,570]){const b=d(n,'机械').bindings.find(b=>b.operation==='enemy-defense-reference-reduction');assert.equal(b.target,'target-enemy');assert.equal(b.appliesPersistentDebuff,false);assert.equal(b.base,'enemy-DEF-for-this-hit');}
 const opening=d(1365,'机械').bindings[0];assert.equal(opening.referencePercent,10);assert.equal(opening.referenceStat,'INT');assert.equal(opening.stat,'STR');assert.equal(opening.durationSeconds,undefined);assert.equal(opening.trigger.event,'battle-start');
 const killer=d(1516,'枪').bindings[0],weak=d(1516,'枪').bindings[1];assert.equal(killer.scope.requiresKillerHit,true);assert.equal(killer.scope.requiresElementWeakHit,undefined);assert.equal(weak.scope.requiresElementWeakHit,true);assert.equal(weak.scope.requiresKillerHit,undefined);assert.deepEqual([killer.valuePercent,weak.valuePercent],[20,20]);
 assert.equal(d(285,'爪').bindings.find(b=>b.requiresCriticalHit).scope.attackType,'unspecified');for(const n of[600,1211])assert.equal(d(n,'爪').bindings.find(b=>b.requiresCriticalHit).scope.attackType,'physical');
});
test('weapon labels complete only assigned fragments and preserve future single-wield progress',()=>{
 for(const[k,tag]of specs)for(const a of registry.tagPasses.find(p=>p.tag===tag).assignments){const e=catalog.entries.find(e=>e.id===a.skillId),dt=e.tagDetails[tag];assert.deepEqual(a.partIds,[...dt.coverage.permissionPartIds,...dt.coverage.conditionPartIds]);for(const b of dt.bindings.filter(b=>b.weaponRole==='condition-benefit'))assert(b.partIds.every(id=>!a.partIds.includes(id)));}
 for(const n of[241,273,281,285,354,396,555,1704])assert.equal(entry(n).judgment,'ready');
 for(const n of[365,410,556,594,619,977,925,1014,1109,1251,1369,1410,1484,1689]){assert.equal(entry(n).judgment,'ready');assert.deepEqual(entry(n).remainingConditions,[]);}
 const earlier=structuredClone(registry);earlier.tagPasses=earlier.tagPasses.filter(p=>p.tag!=='单手');assert(resolveSkillLabels(earlier).find(e=>e.id===source(365).id).remainingConditions.some(s=>s.includes('仅装备一把武器')));const next=entry(365);assert.deepEqual(next.remainingConditions,[]);assert.equal(next.judgment,'ready');assert(!next.remainingEffects.some(x=>x.includes('上限')));assert(next.assignedTags.filter(tag=>!['物理','魔法'].includes(tag)).includes('枪'));
});
function page(tag){const elements=new Map(),get=k=>{if(!elements.has(k))elements.set(k,{value:'',textContent:'',innerHTML:'',hidden:false,listeners:{},addEventListener(k,v){this.listeners[k]=v;},setAttribute(){},focus(){}});return elements.get(k);};vm.runInNewContext(read('../dist/skill-labeling.mjs').replace(/^import .*;\n/gm,'').replace('export function renderLabelTable','function renderLabelTable'),{catalog,skillLabelRows,labelingView,filterLabelRows,URLSearchParams,document:{querySelector:get},window:{SKILL_DATA:data,location:{search:'?tag='+tag},addEventListener(){}},localStorage:{getItem:()=>null,setItem(){assert.fail('Do not modify saved data');}}});return get;}
test('all weapon pages render their horizontal categories, deduplicate, search and invalidate local description edits',()=>{
 for(const[k,tag,ns,groups]of specs){const get=page(k);assert.equal((get('#labelTabs').innerHTML.match(/role="tab"/g)||[]).length,39);assert.equal((get('#labelSubTabs').innerHTML.match(/role="tab"/g)||[]).length,groups+1);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,groups);assert.equal(get('#labelResultCount').textContent,`显示 ${ns.length} / ${ns.length} 个技能（去重）`);const rank=skillLabelRows(data,labelingView(catalog,k)).map(r=>({ready:0,partial:1,unknown:2})[r.judgment]);assert.deepEqual(rank,[...rank].sort((a,b)=>a-b));}
 for(const k of['axe','spear','machine']){const get=page(k);get('#labelSearch').value='两手驱动';get('#labelSearch').listeners.input();assert.match(get('#labelResultCount').textContent,/显示 1 \//);assert.equal((get('#labelTable').innerHTML.match(/<section /g)||[]).length,1);const edits={[`skill:${source(1746).id}`]:{effect:'用户修改了描述'}};const changed=skillLabelRows(data,labelingView(catalog,k),edits).find(e=>e.id===source(1746).id);assert.equal(changed.judgment,'unknown');assert.deepEqual(changed.conditionBindings,{});assert.deepEqual(changed.assignedTags.filter(tag=>!['物理','魔法'].includes(tag)),[]);}
});
