import test from 'node:test';
import assert from 'node:assert/strict';
import {calculateWebsitePanel} from '../dist/panel-calculator.mjs';
import {resolveAttackLayers} from '../dist/attack-layers.mjs';
import {magicBuffLayer,magicBuffOptions} from '../dist/magic-buffs.mjs';
import {combineRuntimeBuffs} from '../dist/runtime-buff-engine.mjs';
import {characterHitStage,migrateCharacterHitDrafts} from '../dist/character-combat-rules.mjs';
import {buildDamageImport} from '../dist/damage-import.mjs';
const runtime=(group,policy='exclusive')=>({layer:'runtime-stat',stackGroup:group,stackPolicy:policy,evidence:'synthetic-test-fixture'});
test('generic STR calculation replaces one group while preserving an independent passive, without character presets',()=>{
 const shared=runtime('test-str-buff'),hp=runtime('test-hp-passive','add');
 const rows=[['buff',40,shared],['passive',20,hp]].map(([id,value,runtime])=>({sourceId:id,sourceName:id,status:'active',rule:{id,effects:[{type:'statBuff',target:'攻击力',value,unit:'%',runtime}]}}));
 const base={hp:1000,mp:100,attack:1000,defense:500,intelligence:600,mind:400};
 const stat=calculateWebsitePanel(base,{rows,context:{}}).stats.attack;
 assert.equal(stat.value,1600);assert.equal(resolveAttackLayers(stat,1600).percent,60);
 const incoming={id:'test-cast',name:'测试Buff',stat:'attack',statPercent:70,runtime:shared};
 const layer=magicBuffLayer(stat,1600,[incoming]);
 assert(layer.ok);assert.equal(layer.percent,90);assert.equal(layer.panel,1900);
 assert.equal(layer.replaced[0].value,40);assert(!layer.inactive.some(b=>b.source==='passive'));
 assert.equal(magicBuffLayer(stat,1900,[incoming]).buffObserved,true);
 // Incoming explicit selection wins, not a guessed 'largest value' policy.
 assert.equal(magicBuffLayer(stat,1600,[{...incoming,statPercent:25}]).percent,45);
 assert.equal(magicBuffLayer(stat,1600,[]),null);
 assert.equal(resolveAttackLayers(stat,1600).percent,60);
 const duplicate={...rows[0],sourceId:'second',sourceName:'second',rule:{id:'second',effects:[{...rows[0].rule.effects[0],value:70}]}};
 assert.equal(calculateWebsitePanel(base,{rows:[...rows,duplicate],context:{}}).values.attack,null);
 assert.equal(combineRuntimeBuffs([{value:10,stat:'attack',runtime:null}]).ok,false);
 const old={value:40,stat:'attack',runtime:shared},next={...old,value:70};
 assert.equal(combineRuntimeBuffs([], [old,next]).ok,false,'array order is not cast order');
 assert.equal(combineRuntimeBuffs([old],[{...next,runtime:{...shared,stackPolicy:'add'}}]).ok,false,'one group cannot silently change its policy');
});
test('Roxy hit stage and migration remain confined to her known spell scope',()=>{
 const entry={sourceId:'water-king',ruleId:'water-ice-hits',effect:{type:'hit',value:2,secondary:.6}},context={attackKind:'magic',element:'ice',magicFamily:'normal',damageType:'magical'};
 assert.equal(characterHitStage('260',entry,context),'core');
 assert.equal(characterHitStage('259',entry,context),undefined);
 assert.equal(characterHitStage('260',entry,{...context,element:'fire'}),undefined);
 assert.equal(characterHitStage('260',entry,{...context,magicFamily:'science'}),undefined);
 const other=buildDamageImport({kind:'last-cloudia-effect-report',characterId:'259',context,rows:[{status:'active',sourceId:entry.sourceId,sourceName:'水王级魔术师',rule:{id:entry.ruleId,effects:[entry.effect]}}]});
 assert.equal(other.hitMultiplier,1);assert(other.blockers.some(b=>b.includes('专属')));assert.equal(other.bossKiller,false);
 const empty=buildDamageImport({kind:'last-cloudia-effect-report',characterId:'259',context,rows:[]});
 assert.equal(empty.hitMultiplier,1);assert.equal(empty.hitDamageRatio,1);assert.equal(empty.bossKiller,false);
 assert.deepEqual(magicBuffOptions({characterId:'259',magic:[]}),[]);
 const drafts={'magic:ice:dual':{hitMultiplier:2,hitDamageRatio:.6,hitScaleStage:'beforeCap'},'s1:one:dual':{hitMultiplier:2,hitDamageRatio:.6,hitScaleStage:'beforeCap'}};
 migrateCharacterHitDrafts('260',{selection:{attack:'magic',preset:'ice',element:'冰'}},drafts);
 assert.equal(drafts['magic:ice:dual'].hitScaleStage,undefined);assert.equal(drafts['s1:one:dual'].hitScaleStage,'beforeCap');
});
